services:
  robine-id:
    environment:
      PGPASSWORD_FILE: /run/secrets/robine_id_postgres_password
      KEY_ENCRYPTION_SECRET_FILE: /run/secrets/robine_id_key_encryption_secret
    secrets:
      - robine_id_postgres_password
      - robine_id_key_encryption_secret

  postgres:
    environment:
      POSTGRES_PASSWORD_FILE: /run/secrets/robine_id_postgres_password
    secrets:
      - robine_id_postgres_password

secrets:
  robine_id_postgres_password:
    file: ${ROBINE_ID_POSTGRES_PASSWORD_PATH:-./deploy/secrets/postgres_password}
  robine_id_key_encryption_secret:
    file: ${ROBINE_ID_KEY_ENCRYPTION_SECRET_PATH:-./deploy/secrets/key_encryption_secret}
