services:
  robine-id:
    environment:
      KEY_ENCRYPTION_SECRET_PREVIOUS_FILE: /run/secrets/robine_id_key_encryption_secret_previous
    secrets:
      - robine_id_key_encryption_secret_previous

secrets:
  robine_id_key_encryption_secret_previous:
    file: ${ROBINE_ID_KEY_ENCRYPTION_SECRET_PREVIOUS_PATH:-./deploy/secrets/key_encryption_secret_previous}
