import Config

# Configure your database
config :robine_id, RobineId.Repo,
  database: Path.expand("../robine_id_dev.db", __DIR__),
  pool_size: 5,
  stacktrace: true,
  show_sensitive_data_on_connection_error: true

# For development, we disable any cache and enable
# debugging and code reloading.
#
# The watchers configuration can be used to run external
# watchers to your application. For example, we can use it
# to bundle .js and .css sources.
config :robine_id, RobineIdWeb.Endpoint,
  # Binding to loopback ipv4 address prevents access from other machines.
  # Change to `ip: {0, 0, 0, 0}` to allow access from other machines.
  http: [ip: {127, 0, 0, 1}],
  check_origin: false,
  code_reloader: true,
  debug_errors: true,
  secret_key_base: "zGu9W2Xm7oTZt6RONigx7jcVQq7rxKBg6RbhT1+jQvrSbFNW7Gpo12Eh1h5yJEc2",
  watchers: [
    esbuild: {Esbuild, :install_and_run, [:robine_id, ~w(--sourcemap=inline --watch)]},
    tailwind: {Tailwind, :install_and_run, [:robine_id, ~w(--watch)]}
  ]

# ## SSL Support
#
# In order to use HTTPS in development, a self-signed
# certificate can be generated by running the following
# Mix task:
#
#     mix phx.gen.cert
#
# Run `mix help phx.gen.cert` for more information.
#
# The `http:` config above can be replaced with:
#
#     https: [
#       port: 4001,
#       cipher_suite: :strong,
#       keyfile: "priv/cert/selfsigned_key.pem",
#       certfile: "priv/cert/selfsigned.pem"
#     ],
#
# If desired, both `http:` and `https:` keys can be
# configured to run both http and https servers on
# different ports.

# Enable dev routes for dashboard and mailbox
config :robine_id, dev_routes: true

# Convenience credentials for the standalone account portal. This setting is
# loaded only in Mix.env() == :dev and is never present in test or production.
config :robine_id, :development_login_prefill, %{
  "identifier" => "admin@example.com",
  "password" => "change-me"
}

# Development-only fallback for the local Penpot integration. Environment
# variables still take precedence, and production does not load this value.
config :robine_id, :configured_secrets, %{
  "PENPOT_OIDC_CLIENT_SECRET" =>
    "j4QgFXnUfpRbOB86wnrErlnB19Ox+26pkz96jjdYD7QFkBxRDtwlMKnzHV0+o954"
}

# Do not include metadata nor timestamps in development logs
config :logger, :default_formatter, format: "[$level] $message\n"

# Set a higher stacktrace during development. Avoid configuring such
# in production as building large stacktraces may be expensive.
config :phoenix, :stacktrace_depth, 20

# Initialize plugs at runtime for faster development compilation
config :phoenix, :plug_init_mode, :runtime

config :phoenix_live_view,
  # Include debug annotations and locations in rendered markup.
  # Changing this configuration will require mix clean and a full recompile.
  debug_heex_annotations: true,
  debug_attributes: true,
  # Enable helpful, but potentially expensive runtime checks
  enable_expensive_runtime_checks: true
